#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Only run tests if changes are in src/ or test/ directories
if git diff --cached --name-only | grep -qE '^(src|test)/'; then
    dotnet husky run --name run-dotnet-test
fi